# Generated by Django 5.2.8 on 2025-11-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cricket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="overs",
            field=models.IntegerField(default=20),
        ),
    ]
