# Generated by Django 5.2.8 on 2025-11-23 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_match_overs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='is_active',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='ball',
            name='innings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='current_innings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ball',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='cricket.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='cricket.team'),
        ),
    ]
