# Generated by Django 5.2.8 on 2025-11-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('umpire', 'Umpire'), ('player', 'Player')], default='player', max_length=10),
        ),
    ]
